### ISSUE TITLE
Request: Fit to screen option

### ISSUE THREAD

**Issue by Sam1066** [alexandrecormier/setwp#1]
Kinda says it all really

**Comment by alexcormier** [comment]
It's already there, using `--fit` or `-f`. Or is that not what you mean?

**Comment by Sam1066** [comment]
Apologies - I meant to say fill (the default mode for setting a wallpaper via system preferences)

**Comment by alexcormier** [comment]
No worries! 😉
Fill screen is also implemented; it's the default if you don't specify any of fit, stretch, center or tile. I could perhaps add a `--fill` option for consistency.

**Comment by Sam1066** [comment]
Thanks! been bugging me for a while 😄
